### ISSUE TITLE
Add Role, Size, and Type information into NPC Actor Sheet

### ISSUE THREAD

**Issue by moroboshi** [cswendrowski/FoundryVTT-Mageflame-SRD#5]
Some stats are not included in the monster description:
- role (wrecker/caster/spoiler/....)
- size (normal/large/huge/2x/3x)
- type (Giant/Undead/Beast)

**Comment by cswendrowski** [comment]
The NPC Actor sheet currently does not have sections for that data to live.

As part of #4, I was planning on copying the naming convention of the Corebook monster compendium being worked on:

https://gyazo.com/a62aad9ddafc2c035b8a912985cf86fd

The format would be `MonsterName (Size Level Role) [Type]`, producing outputs such as `Big Zombie (Large Level 4 Wrecker) [Undead]`.

Would that be acceptable?

**Comment by moroboshi** [comment]
I known that they dont show up on the sheet, but I want to open a ticket to ask for them.
And I could have a better solution, to filter and sort compendiums: I have hacked the code for the Browser Compendium for DnD 5e to work instead with 13th Age, it's here https://github.com/moroboshi/compendium-browser 

The manifest is here: https://raw.githubusercontent.com/moroboshi/compendium-browser/master/module.json

Is possible to filter at the same time multiple compendium by name, type and level and to sort them by name, level and 

I'm struggling with github to release it (I never seriously worked with git/github)

**Comment by cswendrowski** [comment]
After discussion, the next version will include data that the Compendium browser can use for filtering, and the name will remain as-is.

Closing #4 in favor of this approach

**Comment by cswendrowski** [comment]
This is now verifiable in v1.1.0
