### ISSUE TITLE
[DATA] Monster name and data not corresponding

### ISSUE THREAD

**Issue by moroboshi** [cswendrowski/FoundryVTT-Mageflame-SRD#6]
Somewhere in the web scrapping and assembling of the compendium the monster name went out of sync with the data.

Aerial Spore contains the Sporrior data
Sporrior contains the Fungaloid Drudge data
Fungaloid Drudge the Braincap data
Greathoard Elder (Red) the Huge Green Dragon data
ecc...

**Comment by cswendrowski** [comment]
Thanks for reporting this!

I checked about every 25 monsters to see if they were correct, and the last Monster in the SRD (the Dusk Zorigami) is matched up correctly. It's interesting that there was a section that got off track then came back around to matching.

I will investigate and attempt to fix!

**Comment by cswendrowski** [comment]
This is now verifiable in v1.1.0
